# Basic
title: JacobKong's Blog
subtitle: 给今天的你一个机会，去感谢昨天努力的自己！
welcome_message: <a href="http://www.jianshu.com/users/81a8d024af56/latest_articles" target="_blank">也欢迎来我的简书转转！</a>
description: 欢迎来到孔伟杰(@JacobKong_Dev)的博客，目前大四，之前热爱iOS开发:)，目前在学习“机器学习与数据挖掘”领域的相关知识。
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://www.jacobkong.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 了解更多关于我, url: 'http://about.jacobkong.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: JacobKong_Dev
    provider : duoshuo
    duoshuo :
        short_name : jacobkong
    
# Social
social:
    weibo: JacobKong_Dev
    github: JacobKong
    twitter: JacobKong_Dev
    gplus: 109632666247925107848
    mail: kongweijiejacob@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
